sonar.projectName=MicroCRM
sonar.organization=bartsam
sonar.projectKey=bartsam_OC-P7-DevOps
sonar.sourceEncoding=UTF-8

# Sources 
sonar.sources=front/src,back/src/main/java
sonar.tests=front/src,back/src/test/java
sonar.test.inclusions=front/src/**/*.spec.ts,back/src/test/java/**/*.java
sonar.exclusions=front/src/**/*.spec.ts

# Binaries Java
sonar.java.binaries=back/build/classes/java/main

